name: Deploy Cloudflare Worker (API Token)

on:
  push:
    branches: [main]
    paths: ['worker/**']
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy Hello World Worker (using API Token)
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: worker/package.json
          
      - name: Install dependencies
        run: |
          cd worker
          npm install
          
      - name: Deploy to Cloudflare Workers
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          workingDirectory: worker